version: '3'
services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ${WEBROOT}:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend
    php7:
        build:
            context: .
            dockerfile: php7.1-fpm-alpine.dockerfile
        volumes:
            - ${WEBROOT}:/var/www/html
        networks:
            - backend
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - backend
networks:
    backend:
volumes:
    mysql:
